### ISSUE TITLE
Applications, promo, social, docs

### ISSUE THREAD

**Issue by dy** [dy/spect#73]
* [x] readme: all links work
* [x] test: all readme cases covered
* [ ] ~~comparisons: main frameworks, features~~ #147
* [ ] ~~website: simple playground~~ #147
* [ ] ~~benchmark: compare major frameworks~~ #147
* [ ] ~~general docs: clean up docs/examples as much as possible, ux-test~~ #147
* [x] logo: simple triangles-based
* [ ] UI-benchmarks
* [ ] 7GUIs fork and related resourcers https://eugenkiss.github.io/7guis/more
* [ ] ~~FAQ: frameworks, integrations, debug, maintenance, security; make sure no lies told~~ #147
* [ ] Working examples
* [ ] admin-portal
* [ ] react examples
* [ ] components
* [ ] snabbdom list of frameworks
* [ ] https://github.com/google/incremental-dom/blob/master/ECOSYSTEM.md
* [ ] https://mathieuancelin.github.io/js-repaint-perfs/
* [ ] https://github.com/krausest/js-framework-benchmark
* [ ] https://localvoid.github.io/uibench/
* [ ] http://microjs.com/#dom
* [ ] https://github.com/webcomponents/custom-elements-everywhere
* ~~List of app examples~~ #147
* ~~Polished work-through intro~~ #147
* ~~Built with spect~~ #147
* ~~Explain simple form sending first - no need for aspects at all, just direct jquery-like code~~ #147
* [ ] https://github.com/webcomponents/custom-elements-everywhere
* [ ] https://eugenkiss.github.io/7guis/
* [ ] https://github.com/funkia/turbine
* [ ] https://github.com/sveltejs/v2.svelte.dev/tree/master/content/examples
* [ ] https://github.com/luwes/sinuous-sierpinski-triangle-demo
* [ ] https://github.com/luwes/js-diff-benchmark
* [x] toggle deps
* [x] html native elements
* [x] https://github.com/hyperdivision/fast-on-load/issues/6
* [x] sequences of events
* [x] html reducers
* [x] component re-rendering should not destroy state
* [ ] https://github.com/streamich/rx-use use-case

**Comment by dy** [comment]
#### Improvements

* [ ] react aspects: useState, useEffect
* [ ] fx must return destructor
* [ ] suspense as thenable
* [ ] custom events must be able to be defined on elements `<el onCustom=${e => {}} />`
* [ ] react components must be able to be rendered without changes (via preact-compat or some plugin?)

**Comment by dy** [comment]
Only needs benchmark, that's it.
